Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,9 +45,15 @@ jobs:
                ls -l build/libs/
                test -f build/libs/*.jar
 
-      # Step 6: Run Unit test
-      - name: unit test
-        run: ./gradlew clean test
+      - name: Verify JAR file exists
+        run: |
+            ls -l build/libs/
+            if [ -f build/libs/check_weather_app-0.0.1-SNAPSHOT.jar ]; then
+               echo "JAR file exists."
+            else
+               echo "JAR file is missing!" >&2
+            exit 1
+            fi
 
       # Step 7: Run Component test
       - name: component test
